version: '3.7'

services: 
    webapp-server:
        build:
            context: .
            dockerfile: Dockerfile
        image: frontend-iki
        container_name: frontend-iki
        ports: 
            - "8700:8700"